'use client'

import { useEffect } from 'react'

/**
 * Registers the precache service worker generated by scripts/build-sw.mjs.
 * Production-only: sw.js exists only in the static export, and dev should
 * never be served from a cache.
 */
export function SwRegister() {
  useEffect(() => {
    if (process.env.NODE_ENV !== 'production') return
    if (!('serviceWorker' in navigator)) return
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // Offline support is progressive enhancement — never break the app over it.
    })
  }, [])
  return null
}
