/**
 * Generates out/sw.js after `next build` (static export): a precache-everything,
 * cache-first service worker. The whole app must work offline (PRD success
 * criterion 4) — all data is bundled at build time, so the asset universe is
 * closed and enumerable here.
 *
 * The cache version hashes file CONTENTS, not just paths: hashed _next/static
 * filenames change per build, but every index.html keeps its path forever —
 * hashing paths alone would serve stale HTML for eternity under cache-first.
 *
 * No basePath is configured today; if one is ever added, prefix PRECACHE URLs.
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const outDir = fileURLToPath(new URL('../out/', import.meta.url))

const PRECACHE_EXTENSIONS = new Set([
  '.html', '.js', '.css', '.woff2', '.svg', '.png', '.ico', '.webmanifest', '.txt', '.json',
])

const files = []
for (const entry of readdirSync(outDir, { recursive: true })) {
  const path = join(outDir, String(entry))
  if (!statSync(path).isFile()) continue
  const rel = relative(outDir, path).split(sep).join('/')
  if (rel === 'sw.js') continue
  const dot = rel.lastIndexOf('.')
  if (dot === -1 || !PRECACHE_EXTENSIONS.has(rel.slice(dot))) continue
  files.push(rel)
}
files.sort()

const hash = createHash('sha256')
for (const rel of files) {
  hash.update(rel)
  hash.update(readFileSync(join(outDir, rel)))
}
const version = hash.digest('hex').slice(0, 12)
const urls = files.map((rel) => `/${rel}`)

const sw = `/* Generated by scripts/build-sw.mjs — do not edit. */
const CACHE = 'precache-${version}'
const PRECACHE = ${JSON.stringify(urls)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    // Deep links carry query strings (URL-encoded calculator state) — match on
    // the pathname only, trying the trailing-slash export layout both ways.
    const path = url.pathname
    event.respondWith(
      caches.open(CACHE).then(async (cache) => {
        return (
          (await cache.match(path)) ||
          (await cache.match(path + (path.endsWith('/') ? '' : '/') + 'index.html')) ||
          (await cache.match(path + 'index.html')) ||
          fetch(request).catch(() => cache.match('/404.html')) ||
          cache.match('/404.html')
        )
      }),
    )
    return
  }

  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const cached = await cache.match(request)
      return cached || fetch(request)
    }),
  )
})
`

writeFileSync(join(outDir, 'sw.js'), sw)
console.log(`sw.js: ${files.length} precached files, cache precache-${version}`)
